import type { CSSProperties } from 'react';

// Shared, typed utility vocabulary for control styles. Values follow the synced
// frontend theme. A few component-specific dimensions are kept here because the
// upstream scale has no matching token.
export const utilities = {
  'absolute': { position: 'absolute' },
  'accent-blue500': { accentColor: 'var(--blue500)' },
  'animate-spin': { animation: 'spin .7s linear infinite' },
  'aspect-square': { aspectRatio: '1' },
  'bg-buttonDestructiveBg': { background: 'var(--buttonDestructiveBg)' },
  'bg-buttonGhostBg': { background: 'var(--buttonGhostBg)' },
  'bg-buttonPrimaryBg': { background: 'var(--buttonPrimaryBg)' },
  'bg-buttonSecondaryBg': { background: 'var(--buttonSecondaryBg)' },
  'bg-mainBackground': { background: 'var(--mainBackground)' },
  'bg-strokeDark': { background: 'var(--strokeDark)' },
  'bg-strokeLight': { background: 'var(--strokeLight)' },
  'bg-transparent': { background: 'transparent' },
  'block': { display: 'block' },
  'border-0': { border: '0' },
  'border-b-current-semi': { borderBottom: '1.5px solid currentColor' },
  'border-current-2': { border: '2px solid currentColor' },
  'border-r-current-semi': { borderRight: '1.5px solid currentColor' },
  'border-r-transparent': { borderRightColor: 'transparent' },
  'border-strokeDark': { border: 'var(--borderWidthThin) solid var(--strokeDark)' },
  'border-strokeLight': { border: 'var(--borderWidthThin) solid var(--strokeLight)' },
  'cursor-inherit': { cursor: 'inherit' },
  'cursor-pointer': { cursor: 'pointer' },
  'flex': { display: 'flex' },
  'flex-none': { flex: 'none' },
  'font-FactorA': { fontFamily: 'var(--fontFactorA)' },
  'font-Inter': { fontFamily: 'var(--fontInter)' },
  'font-inherit': { font: 'inherit' },
  'font-medium': { fontWeight: 'var(--fontWeightMedium)' },
  'gap-12': { gap: 'var(--space12)' },
  'gap-4': { gap: 'var(--space4)' },
  'gap-8': { gap: 'var(--space8)' },
  'h-1': { height: 'var(--borderWidthThin)' },
  'h-16': { height: 'var(--sizeIconSmall)' },
  'h-20': { height: 'var(--space20)' },
  'h-24': { height: 'var(--sizeIconMedium)' },
  'h-32': { height: 'var(--sizeIconLarge)' },
  'h-40': { height: 'var(--space40)' },
  'h-55': { height: '55px' },
  'h-56': { height: 'var(--fontSize56)' },
  'h-7': { height: '7px' },
  'h-auto': { height: 'auto' },
  'h-full': { height: '100%' },
  'inline-block': { display: 'inline-block' },
  'inline-flex': { display: 'inline-flex' },
  'items-center': { alignItems: 'center' },
  'justify-center': { justifyContent: 'center' },
  'leading-16': { lineHeight: 'var(--lineHeight16)' },
  'leading-20': { lineHeight: 'var(--lineHeight20)' },
  'left-0': { left: '0' },
  'm-0': { margin: '0' },
  'max-h-menu': { maxHeight: '400px' },
  'max-w-menu': { maxWidth: 'min(400px, 90vw)' },
  'mb-8': { marginBottom: 'var(--space8)' },
  'min-h-menu-item': { minHeight: '41px' },
  'min-h-textarea': { minHeight: '80px' },
  'min-w-0': { minWidth: '0' },
  'min-w-select': { minWidth: '150px' },
  'opacity-0': { opacity: '0' },
  'outline-0': { outline: '0' },
  'overflow-y-auto': { overflowY: 'auto' },
  'p-0': { padding: '0' },
  'p-8': { padding: 'var(--space8)' },
  'px-12': { padding: '0 var(--space12)' },
  'px-16': { padding: '0 var(--space16)' },
  'py-8-px-12': { padding: 'var(--space8) var(--space12)' },
  'relative': { position: 'relative' },
  'rotate-caret': { transform: 'rotate(45deg) translateY(-2px)' },
  'rounded-full': { borderRadius: 'var(--radiusRound)' },
  'rounded-large': { borderRadius: 'var(--radiusLarge)' },
  'rounded-medium': { borderRadius: 'var(--radiusMedium)' },
  'rounded-round': { borderRadius: 'var(--radiusRound)' },
  'rounded-small': { borderRadius: 'var(--radiusSmall)' },
  'shadow-inputLarge': { boxShadow: 'var(--shadowInputLarge)' },
  'shadow-medium': { boxShadow: 'var(--shadowMedium)' },
  'shadow-none': { boxShadow: 'none' },
  'shadow-small': { boxShadow: 'var(--shadowSmall)' },
  'text-13': { fontSize: 'var(--fontSize13)' },
  'text-14': { fontSize: 'var(--fontSize14)' },
  'text-18': { fontSize: 'var(--fontSize18)' },
  'text-blue300': { color: 'var(--blue300)' },
  'text-buttonDestructiveText': { color: 'var(--buttonDestructiveText)' },
  'text-buttonGhostText': { color: 'var(--buttonGhostText)' },
  'text-buttonPrimaryText': { color: 'var(--buttonPrimaryText)' },
  'text-buttonSecondaryText': { color: 'var(--buttonSecondaryText)' },
  'text-inherit': { color: 'inherit' },
  'text-left': { textAlign: 'left' },
  'text-textLinkDefault': { color: 'var(--textLinkDefault)' },
  'text-textPrimary': { color: 'var(--textPrimary)' },
  'text-textSecondary': { color: 'var(--textSecondary)' },
  'top-menu': { top: 'calc(100% + var(--space4))' },
  'tracking-6': { letterSpacing: '.06em' },
  'transition-colors': { transition: 'background-color var(--transitionDefault)' },
  'underline': { textDecoration: 'underline' },
  'uppercase': { textTransform: 'uppercase' },
  'w-1': { width: 'var(--borderWidthThin)' },
  'w-16': { width: 'var(--sizeIconSmall)' },
  'w-24': { width: 'var(--sizeIconMedium)' },
  'w-36': { width: 'var(--space36)' },
  'w-7': { width: '7px' },
  'w-full': { width: '100%' },
  'whitespace-nowrap': { whiteSpace: 'nowrap' },
  'z-menu': { zIndex: '20' },
} satisfies Record<string, CSSProperties>;

export type Utility = keyof typeof utilities;

export function sx(...parts: (Utility | CSSProperties | false | undefined)[]): CSSProperties {
  const style: CSSProperties = {};
  for (const part of parts) {
    if (part) Object.assign(style, typeof part === 'string' ? utilities[part] : part);
  }
  return style;
}
